---
title: Final Project Review Hemme / Cavros 
author: Irene Cavros
date: 04/28/2023
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Spatial Investigation and Exploration of Factors influencing HIV-related Mortality

Name of project author(s): Hayley Hemme

Name of project reviewer: Irene Cavros


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/knits into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation

How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?


### Feedback and Comments

Summary/abstract: 
- What you have written is very succinct and clear! 
- Consider adding a few sentences which start to prime us on the actual results of your research and what they mean.

Introduction Section:
- Very clear and well detailed.
- I know it is a fairly commonplace acronym but it may be good to just clarify what the HIV and AIDS abbreviations stand for at the top. 

Background section: 
- Great job weaving citations into the text!
- Consider adding a paragraph that is specific to race and HIV.


### Summary assessment (PICK ONE, DELETE THE OTHERS)
* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

Your research question and hypothesis in section 2.1 are clear. You also explain them more informally early on in the manuscript, limiting the possibility for any confusion.


### Summary assessment
* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 


### Feedback and Comments

Great description of the data sources used for your research! I have no suggestions for improvement. 


### Summary assessment
* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?


### Feedback and Comments

- Nice description of the cleaning that was done and I liked that you specifically called out details like which variables were suppressed due to small counts.
-Consider adding a high level figure summarizing data before you go into outcome variables.


### Summary assessment
* essentially no weaknesses in wrangling and exploratory component


## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?


### Feedback and Comments

- PCA in the data cleaning step was well described. 
- The explanation in the statistical analysis subsection in section 3 plus the analysis section 4 made sense to me and were very clear. 


### Summary assessment
* strong and reasonable analysis


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 


### Feedback and Comments

- Table 1 was a nice high level overview of the problem before digging into more complex analyses. 
- I'm not 100% certain what I am looking at in figure 1. Could you explain in greater detail what you are presenting? 
- I think you may have added table 3 twice into the body of the manuscript. It's a nice visual though! 
- Table 2: change title to figure 2 since it is a map. Again, a great visual though!
- Are all 4 figures after table 2 considered as one figure? Also I recommend changing the title to this figure for clarity. 
- When we get to section 5.3 Full analysis, the narrative accompanying your visuals is a bit sparce. I recommend fleshing this out. 


### Summary assessment
* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?


### Feedback and Comments

- Have you pushed your discussion and conclusions section? They appear blank for me unfortunately.


### Summary assessment
* major parts of discussion missing or wrong


## Further comments

Well done! There are some notes/questions I jotted down in my project review that became clear later in the manuscript but I wanted to keep them in this file anyways because it can give you an idea of what the reader is grasping at what point in the manuscript and what might need further clarification earlier on.


# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?


### Feedback and Comments

- The numbering of code files was a great way to ensure everything is run in the appropriate order.
- There are a few files in your project that I am unsure of their purpose: `outputs_code.Rmd`, `tes2.R`, and `tes1.R`
-Consider changing the folder label for `results` to something like visuals, figures, etc since your full results are elsewhere.

### Summary assessment
* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 


### Feedback and Comments

- You do a great job going through your decision making process throughout the analysis section of the manuscript! 
- Some of your code files are extremely well documented like `p4_mapping.Rmd` but others could do with some additional narrative to accompany the code


### Summary assessment
* fully and well documented


## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

- All processing code was fully reproducible. 
- Error in `1_EDA_alt` file: line 302 (error in select, unused argument)
- Error in `2_PCA_alt` file: line 13 (error in select, unused argument - was not able to run the rest of the chunks after this error)
- Error in `3_model_alt` file: line 13 (error in select, unused argument)


### Summary assessment
* small parts not reproducible or required manual intervention


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?


### Feedback and Comments

Your project is very robust in terms of thoroughness! The research question was fully addressed. 


### Summary assessment
* strong level of thoroughness


## Further comments

_Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project._

Wonderful job, Hayley! My comments/suggestions are very minute and perhaps nit picky but it's evident you put a lot of time and effort into this project! Overall, most of my suggestions are just to provide clarity but you really got all the hard parts down. Congratulations on all your excellent work! 



