```{r message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
library(MASS)
library(spatialreg)
library(spdep)
```

```{r}
df <- readRDS(here("data/processed_data/race_new.rds"))
us_nabs <- readRDS(here("data/processed_data/us_nabs.rds"))

#Subset to contiguous states
us_nabs <- us_nabs %>%
  filter(!grepl("AK", StateCode),
         !grepl("HI", StateCode), 
         !grepl("DC", StateCode))

df <- df %>% 
  filter(!grepl("Alaska", State),
         !grepl("Hawaii", State)) %>% 
  mutate(log_rate = log(`Death Rate (estimated)`+ 1))
```

Setting up functions for models
```{r}
  #poisson
pois_function <- function(race) {
  pois_race <- glm(`Death Cases` ~ `Median Household Income` +
                       `Percent High School Education` +
                       offset(log(`Population`)),
                     data = df[df$Race == race,],
                     family = poisson)
  print(summary(pois_race))
}

  #Negative binomial
nb_function  <- function(race) {
  neg_bin_race <- glm.nb(`Death Cases` ~ `Median Household Income` +
                              `Percent High School Education` + 
                              offset(log(`Population`)),
                            data = df[df$Race == race,])
  print(summary(neg_bin_race))
}

  #Fitting CAR model (requires neighbors)
car_function <- function(race) {   
  # filter race_df by the selected race/ethnicity
  df <- df[df$Race == race,] 
  
  
  h_race_df <- matrix(0, nrow(df), nrow(df))
  h_race_df[cbind(match(us_nabs$StateCode, df$`State Abbreviation`),
                  match(us_nabs$NeighborStateCode, df$`State Abbreviation`))] <- 1
  
  nablist_race_df <- mat2listw(h_race_df, style = "W")
  
  car_race <- spautolm(`Death Cases` ~ `Median Household Income` +
                              `Percent High School Education` + 
                              offset(log(`Population`)),
                           data = df,
                           listw = nablist_race_df,
                           family = "CAR")
  print(summary(car_race))
}
```

Fitting Poisson models
```{r}
pois_function("Black")
```

```{r}
sink(here("results/pois_summary_black.txt"))
pois_function("Black")
sink()
```

```{r}
pois_function("Hispanic")
```

```{r}
sink(here("results/pois_summary_hispanic.txt"))
pois_function("Hispanic")
sink()
```

```{r}
pois_function("Multiple")
```

```{r}
sink(here("results/pois_summary_multiple.txt"))
pois_function("Multiple")
sink()
```

```{r}
pois_function("White")
```

```{r}
sink(here("results/pois_summary_white.txt"))
pois_function("White")
sink()
```

Fitting Negative binomial models
```{r}
nb_function("Black")
```
```{r}
sink(here("results/nb_summary_black.txt"))
nb_function("Black")
sink()
```


```{r}
nb_function("Hispanic")
```
```{r}
sink(here("results/nb_summary_hispanic.txt"))
nb_function("Hispanic")
sink()
```

```{r}
nb_function("Multiple")
```

```{r}
sink(here("results/nb_summary_multiple.txt"))
nb_function("Multiple")
sink()
```

```{r}
nb_function("White")
```

```{r}
sink(here("results/nb_summary_white.txt"))
nb_function("White")
sink()
```

The NB model accounting for overdispersion fits better than the poisson model.

Fitting CAR models
```{r}
car_function("Black")
```

```{r}
sink(here("results/car_summary_black.txt"))
car_function("Black")
sink()
```

```{r}
car_function("Hispanic")
```

```{r}
sink(here("results/car_summary_hispanic.txt"))
car_function("Hispanic")
sink()
```

```{r}
car_function("Multiple")
```
```{r}
sink(here("results/car_summary_multiple.txt"))
car_function("Multiple")
sink()
```

```{r}
car_function("White")
```
```{r}
sink(here("results/car_summary_white.txt"))
car_function("White")
sink()
```
The model accounting for spatial variation provide the best fit.

Creating function that subsets by specified race, and compute/ plots Moran's I and lisa.
```{r}
spacy_function <- function(race) {
  # filter race_df by the selected race/ethnicity
  df <- df[df$Race == race,]
  
  h_race_df <- matrix(0, nrow(df), nrow(df))
  h_race_df[cbind(match(us_nabs$StateCode, df$`State Abbreviation`),
  match(us_nabs$NeighborStateCode, df$`State Abbreviation`))] <- 1
  
  nablist_race_df <- mat2listw(h_race_df, style = "W")

 # plot Moran's I
  print(moran.test(df$BOX, nablist_race_df, zero.policy = TRUE, randomisation = FALSE))
  moran.plot(df$BOX, nablist_race_df, zero.policy = TRUE)
  
  # calculate and print LISA statistics
  lisa_race <- localmoran(df$`Ratio Observed/ Expected`, nablist_race_df)
  summary(lisa_race[,1])
}
```

```{r}
spacy_function("Black")
```

```{r}
png(here("results/moran_black.png"))
sink(here("results/spacy_summary_black.txt"))
spacy_function("Black")
sink()
dev.off()
```

```{r}
spacy_function("Hispanic")
```

```{r}
png(here("results/moran_hispanic.png"))
sink(here("results/spacy_summary_hispanic.txt"))
spacy_function("Hispanic")
sink()
dev.off()
```

```{r}
spacy_function("Multiple")
```

```{r}
png(here("results/moran_multiple.png"))
sink(here("results/spacy_summary_multiple.txt"))
spacy_function("Multiple")
sink()
dev.off()
```

```{r}
spacy_function("White")
```

```{r}
png(here("results/moran_white.png"))
sink(here("results/spacy_summary_white.txt"))
spacy_function("White")
sink()
dev.off()
```

```{r}
save.image(here("data/processed_data/race_env.rds"))
```
