```{r}
library(here)
library(tidyverse)
library(spdep)
library(spatialreg)

df <- readRDS(here("data/processed_data/race_new.rds"))
us_nabs <- readRDS(here("data/processed_data/us_nabs.rds"))

#Subset to contiguous states
us_nabs <- us_nabs %>%
  filter(!grepl("AK", StateCode),
         !grepl("HI", StateCode), 
         !grepl("DC", StateCode))
```

The following code performs a CAR model, provides a summary, and pulls fitted values. I subset by each race. 
```{r}
black <- df %>% filter(Race == "Black") 

h_black_df <- matrix(0, nrow(black), nrow(black))
h_black_df[cbind(match(us_nabs$StateCode, black$`State Abbreviation`),
                 match(us_nabs$NeighborStateCode, black$`State Abbreviation`))] <- 1

nablist_black_df <- mat2listw(h_black_df, style = "W")

car_black <- spautolm(BOX ~ `Percent Living in Poverty` + 
                        `Percent High School Education`,
                      listw = nablist_black_df, 
                      data = black,
                      family = "CAR")
print(summary(car_black))

##pull fitted values
black$fitted_values <- car_black$fit$fitted.values
```
We will use the 

```{r}
##
multiple <- df[df$Race == "Multiple",] 

h_multiple_df <- matrix(0, nrow(multiple), nrow(multiple))
h_multiple_df[cbind(match(us_nabs$StateCode, multiple$`State Abbreviation`),
                    match(us_nabs$NeighborStateCode, multiple$`State Abbreviation`))] <- 1

nablist_multiple_df <- mat2listw(h_multiple_df, style = "W")

car_multiple <- spautolm(BOX ~ `Percent Living in Poverty` + 
                        `Percent High School Education`,
                         data = multiple,
                         listw = nablist_multiple_df,
                         family = "CAR")
print(summary(car_multiple))

multiple$fitted_values <- car_multiple$fit$fitted.values
```

```{r}
hispanic <- df[df$Race == "Hispanic",] 

h_hispanic_df <- matrix(0, nrow(hispanic), nrow(hispanic))
h_hispanic_df[cbind(match(us_nabs$StateCode, hispanic$`State Abbreviation`),
                    match(us_nabs$NeighborStateCode, hispanic$`State Abbreviation`))] <- 1

nablist_hispanic_df <- mat2listw(h_hispanic_df, style = "W")

car_hispanic <- spautolm(BOX ~ `Percent Living in Poverty` + 
                        `Percent High School Education`,
                         data = hispanic,
                         listw = nablist_hispanic_df,
                         family = "CAR")
print(summary(car_hispanic))

fitted_values_hispanic <- car_hispanic$fit$fitted.values

hispanic$fitted_values <- fitted_values_hispanic 
```

```{r}
white <- df[df$Race == "White",] 

h_white_df <- matrix(0, nrow(white), nrow(white))
h_white_df[cbind(match(us_nabs$StateCode, white$`State Abbreviation`),
                 match(us_nabs$NeighborStateCode, white$`State Abbreviation`))] <- 1

nablist_white_df <- mat2listw(h_white_df, style = "W")

car_white <- spautolm(BOX ~ `Percent Living in Poverty` + 
                        `Percent High School Education`,
                      data = white,
                      listw = nablist_white_df,
                      family = "CAR")
print(summary(car_white))

fitted_values_white <- car_white$fit$fitted.values

white$fitted_values <- fitted_values_white 

```

now let's combine then back into one dataframe.
```{r}
race_fit <- list(black, multiple, hispanic, white)

race_fit <-reduce(race_fit, full_join)

saveRDS(race_fit, here("data/processed_data/race_fit.rds"))
```