```{r, echo=FALSE, message=FALSE}
library(knitr)
library(tidyverse)
library(here)
```

```{r}
sex_df <- readRDS(here("data/processed_data/sex_df.rds"))
```
Let's find the HIV death rate by sex
```{r}
sex_df <- sex_df %>% 
  mutate(Male_Rate = round(`Male Death Cases`/pop_male*1e5),
         Female_Rate = round(`Female Death Cases`/pop_female*1e5)) %>% 
  select(!`Year`)
```

Next, let's find the expected number of HIV deaths. First, we'll calculate lambda.
```{r}
lambda_male <- sex_df %>% drop_na(`Male Death Cases`) %>% 
  drop_na(pop_male) %>% 
  summarize(lambda_male = sum(`Male Death Cases`)/sum(pop_male)) %>%
  as.numeric()

lambda_female <- sex_df %>% drop_na(`Female Death Cases`) %>% 
  drop_na(pop_female) %>% 
  summarize(lambda_female = sum(`Female Death Cases`)/sum(pop_female)) %>%
  as.numeric()

sex_df <- sex_df %>%
  mutate(male_exp_deaths = round(pop_male * lambda_male),
         female_exp_deaths = round(pop_female *  lambda_female))
```

```{r}
sex_df <- sex_df %>% 
  mutate(ratio_OE_male = `Male Death Cases` / male_exp_deaths,
         ratio_OE_female = `Female Death Cases` / female_exp_deaths)
```

```{r}
female_df <- sex_df %>% select(1:3, contains("female")) 
male_df <- sex_df %>% select(1:3, !contains("female")) 

female_df <- female_df %>% 
  mutate(Sex = "Female") %>% 
 rename("Death Rate (AIDSVu)" = `Female Death Rate`,
        "Population" = pop_female,
        "Death Cases" = "Female Death Cases",
        "New Diagnoses Rate" = "New Diagnoses Female Rate",
        "New Diagnoses Cases" = "New Diagnoses Female Cases",
        "Percentage Received Care" = "Female_rec_care_percent",
        "Percentage Virally Suppressed" = "Female_viral_sup_percent",
        "HIV Prevalence Rate" = "Female Rate",
        "Prevalent HIV Cases" = "Female Cases",
        "Expected Death Cases" = female_exp_deaths,
        "Ratio Observed/Expected" = ratio_OE_female,
        "Death Rate (estimated)" = Female_Rate) 

male_df <- male_df %>% 
  mutate(Sex = "Male") %>% 
 rename("Death Rate (AIDSVu)" = `Male Death Rate`,
        "Population" = pop_male,
        "Death Cases" = "Male Death Cases",
        "New Diagnoses Rate" = "New Diagnoses Male Rate",
        "New Diagnoses Cases" = "New Diagnoses Male Cases",
        "Percentage Received Care" = "Male_rec_care_percent",
        "Percentage Virally Suppressed" = "Male_viral_sup_percent",
        "HIV Prevalence Rate" = "Male Rate",
        "Prevalent HIV Cases" = "Male Cases",
        "Expected Death Cases" = male_exp_deaths,
        "Ratio Observed/Expected" = ratio_OE_male,
        "Death Rate (estimated)" = Male_Rate) %>% 
  select(!`State Rate`)

sex_df <- full_join(female_df, male_df)

```

```{r}
saveRDS(sex_df, here("data/processed_data/sex_df_cleaned.rds"))
```